### PR TITLE
cli: Improve CLI documentation

### PR DESCRIPTION
**Pull request by rohany**
Greatly improve CLI document after Iliano's feedback that the first version was mostly useless.

This update adds in more background, detailed documentation about each argument and command, and example usages.

### CODE REVIEW

**Comment by umutacar** [comment]
One concern is that this setup encourages users to store their passes as clear text.  This can be dangerous,  for example, on shared fire systems such as AFS users home directory is usually readable by other users isn't it?  We don't want to start a game where students fish for each other's diderot passes and login as them.

**Comment by rohany** [comment]
Ah, the fact that home directories are not private on afs is a fact I forgot about. I like having a place that the CLI looks by default for credentials so that you don't have to use the flag with the CLI. Perhaps an environment variable holding a path to the credentials file (which could be stored in the afs user private folder) is a better strategy for now (without having to do some sort of hashing/encoding of passwords).

**Comment by umutacar** [comment]
Environment variables are usually set in some kind of .bash_script which is usually on the user's home page and is readable by everyone :)

**Comment by rohany** [comment]
I meant an environment variable pointing which points to a file -- this file can then be stored inside the private directory.

**Comment by umutacar** [comment]
Ok that might be ok for now.   is there a default ./private on AFS?

**Comment by rohany** [comment]
Every user has a default ~/private folder where students store their homeworks etc.

**Comment by umutacar** [comment]
ok, good. you can look for credentials in ./private/.diderot by default if the env variable is not defined.  so this way the students don't have to set anything for the basic use.

**Comment by rohany** [comment]
This is ready for another look -- thanks to help from gaurav there is better solution to this!

**Pull request merged**
